[bun]
keywords = ["bun", "bun.sh"]
content = """
Bun is a modern JavaScript runtime like Node or Deno. It was built from scratch to focus on three main things:
â€¢ Start fast (it has the edge in mind).
â€¢ New levels of performance (extending JavaScriptCore, the engine).
â€¢ Being a great and complete tool (bundler, transpiler, package manager).

Read more [here](<https://bun.sh/>)
"""

[bug]
keywords = ["bug", "report", "bugs"]
content = """
Found a bug in bun?
â€¢ If you are unsure, first discuss your bug in <#887787428973281300> or <#995247410794217553>
â€¢ [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=1-bug-report.yml>) and fill out the given template
"""

[feature-request]
keywords = ["feature-request", "feature", "request"]
content = """
Any idea what to add to bun?
â€¢ Please consider if this is a request for bun, not for other 3rd party packages
â€¢ [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=2-feature-request.yml>) and fill out the given template
"""

[contributing-tags]
keywords = ["contributing-tags", "contributing", "tags"]
content = """
To create or update tag, check [xHyroM/bun-discord-bot#contributing-tags](<https://github.com/xHyroM/bun-discord-bot/#contributing-tags>)
"""

[hono]
keywords = ["hono", "express", "server", "routes"]
content = """
**Hono - [ç‚Ž] means flameðŸ”¥ in Japanese**
â€¢ Is a small, simple, and ultrafast web framework for Cloudflare Workers, Deno, Bun, and others

[Bun supports partially express, but you can also use hono.](<https://github.com/honojs/hono#bun>)
"""

[not-same-file-system]
keywords = ["not-same-file-system", "backend copyfile", "copyfile"]
content = """
**error: NotSameFileSystem installing [package]**

You have old bun. Use `bun upgrade` to upgrade.
If you have problems with upgrade, reinstall bun using `curl https://bun.sh/install | bash`
"""

[windows]
keywords = ["windows", "windows support"]
content = """
Bun does not currently have support for Windows, so you must use WSL (Windows Subsystem for Linux).
To install WSL, check [microsoft documentation](<https://docs.microsoft.com/en-us/windows/wsl/install>)
"""

[io-uring-is-not-supported]
keywords = ["io-uring-is-not-supported", "io uring", "not supported", "support", "linux", "kernel", "update"]
content = """
**error: Linux kernel version doesn't support io_uring, which Bun depends on**

To fix this error, you need to update Linux kernel.
If you are using the Windows Subsystem for Linux, do:
  **1.** Open powershell as administrator
  **2.** Run:
     â€¢ wsl --set-version <disto name> 2
       â€¢ If it throws `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.`, turn on Virtual Machine Platform in Windows Features and then rerun this command.
       â€¢ PS: You can get distro name from `wsl --list -v` 
     â€¢ wsl --update
     â€¢ wsl --shutdown

If that doesn't work (and you're on a Windows machine), try this:
  **1.** Open Windows Update
  **2.** Download any updates to Windows Subsystem for Linux
"""

[illegal-instruction]
keywords = ["illegal-instruction", "core-dumped", "dumped", "core", "illegal"]
content = """
**Illegal instruction - core dumped**

Update to latest version using:
+++
curl https://bun.sh/install | bash
+++

or install latest *-baseline build from [GitHub Releases](https://github.com/oven-sh/bun/releases)
"""

[why-zig]
keywords = ["why-zig", "zig", "zig-lang", "zig lang bun"]
content = """
[**Zig**](https://ziglang.org/) is a general-purpose programming language and toolchain for maintaining **robust**, **optimal** and **reusable** software.

Its **low-level control over memory** and **lack of hidden control flow**, whilst retaining **simplicity** and **flexibility**, makes building _fast_ software (in development time as well) relatively easier.
"""
